config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create]
  resources :races, only: [:index, :show]
  
  namespace :admin do
    resources :reviews, only: [:index, :update]
  end
  
  namespace :items do
    resources :hydration_packs, only: [:index]
    resources :outerwear, only: [:index]
    resources :shoes, only: [:index]
    resources :base_layers, only: [:index]
  end
  resources :items, only: [:show]
  
  get "/auth/strava/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < ApplicationController
  before_action :require_admin
  
  def index
    @user = current_user
    set_reviews
  end
  
  def update
    r = Review.find(params[:id])
    r.update_attributes({
      reviewed: true,
      approved: params[:approved]
    })
    redirect_to admin_reviews_path
  end
  
  private
  
  def require_admin
    render file: "/public/404" unless current_admin?
  end
  
  def set_reviews
    @pending_reviews = Review.where(reviewed: false)
    @rejected_reviews = Review.where("reviewed = ? AND approved = ?", true, false)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @race_options = Race.all.by_name_date.map do |r|
      [[r.date.year, r.name].join(' '), r.id]
    end
    @item_options = Item.all.by_brand_model.map do |i|
      [[i.sex, i.brand, i.model].join(' '), i.id]
    end
    @type_options = ["Shoe", "HydrationPack", "BaseLayer", "Outerwear"]
    @review = Review.new
    @review.item = Item.new
    @review.race = Race.new
    @user = current_user
  end
  
  def create
    @user = current_user
    review = Review.new(review_params)
    review.update_attributes({
      user: @user,
      race: check_for_race_input,
      item: check_for_item_input,
      strava_user_total: @user.update_strava_user_total
    })
    redirect_to user_path(@user)
  end
  
  
  
  private
  
  def check_for_race_input
    if params[:review][:race_id].to_i > 0
      Race.find(params[:review][:race_id])
    else
      race = Race.new(race_params)
      coordinates = fetch_coordinates(race)
      race.lat = coordinates[0]
      race.lon = coordinates[1]
      weather = fetch_weather(race)
      race.temp_high = weather[0]
      race.temp_low = weather[1]
      race.climate = weather[2]
      race.save
      race
    end
  end
  
  def check_for_item_input
    if params[:review][:item_id].to_i > 0
      Item.find(params[:review][:item_id])
    else
      Item.create(item_params)
    end
  end
  
  def race_params
    params.require(:race).permit(:name, :distance, :location, :date)
  end
  
  def item_params
    params.require(:item).permit(:type, :brand, :model, :sex, :image_path)
  end
  
  def review_params
    params.require(:review).permit(:item_id, :race_id, :user_id, :rating, :comments)
  end
  
  def fetch_coordinates(race)
    geo_service = GoogleGeocodeApiService.new(race.location)
    raw_data = geo_service.get_coordinates
    [raw_data[:results][0][:geometry][:location][:lat], raw_data[:results][0][:geometry][:location][:lng]]
  end
  
  def fetch_weather(race)
    weather_service = DarkSkyApiService.new
    raw_data = weather_service.historical_weather(race.lat, race.lon, race.date)
    [raw_data[:daily][:data][0][:temperatureMax].to_f, raw_data[:daily][:data][0][:temperatureMin].to_f,
    raw_data[:daily][:data][0][:summary]]
  end
end

app/views/admin/reviews/index.html.erb
<h3 class="text-center">Admin Page</h3>
<hr>

<div class='text-center' class='pending-reviews'>
  <% cache cache_key_for(Review, "pending") do %>
  <h4>Pending Reviews</h4>
  <table>
    <tr>
      <th>User</th>
      <th>Review Date</th>
      <th>Rating</th>
      <th>Race</th>
      <th>Comments</th>
      <th>Approve</th>
      <th>Reject</th>
    </tr>
    <% @pending_reviews.each do |review| %>
      <tr class="pending-review">
        <td><%= link_to review.user.strava_id, "https://www.strava.com/athletes/#{review.user.strava_id}" %>
        <td><%= review.created_at.to_date %></td>
        <td><%= review.rating %></td>
        <td><%= link_to "#{review.race.name}", race_path(review.race) %></td>
        <td><%= review.comments %></td>
        <td><%= link_to "Approve", admin_review_path(review, approved: true), { method: :patch } %>
        <td><%= link_to "Reject", admin_review_path(review, approved: false), { method: :patch } %>
      </tr>
    <% end %>
  </table>
  <hr>
  <% end %>
</div>

<div class='text-center' class='rejected-reviews'>
  <% cache cache_key_for(Review, "rejected") do %>
  <h4>Rejected Reviews</h4>
  <table>
    <tr>
      <th>User</th>
      <th>Review Date</th>
      <th>Rating</th>
      <th>Race</th>
      <th>Comments</th>
      <th>Approve</th>
    </tr>
    <% @rejected_reviews.each do |review| %>
      <tr class="rejected-review">
        <td><%= link_to review.user.strava_id, "https://www.strava.com/athletes/#{review.user.strava_id}" %>
        <td><%= review.created_at.to_date %></td>
        <td><%= review.rating %></td>
        <td><%= review.race.name %></td>
        <td><%= review.comments %></td>
        <td><%= link_to "Approve", admin_review_path(review, approved: true), { method: :patch } %>
      </tr>
    <% end %>
  </table>
  <hr>
  <% end %>
</div>