config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create]
  resources :races, only: [:index, :show]
  
  namespace :admin do
    resources :reviews, only: [:index, :update]
  end
  
  namespace :items do
    resources :hydration_packs, only: [:index]
    resources :outerwear, only: [:index]
    resources :shoes, only: [:index]
    resources :base_layers, only: [:index]
  end
  resources :items, only: [:show]
  
  get "/auth/strava/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/models/race.rb
class Race < ApplicationRecord
  scope :by_name_date, -> { order(:name, date: "DESC") }
  
  validates :name, presence: true
  validates :location, presence: true
  validates :date, presence: true
  validates :lat, presence: true
  validates :lon, presence: true
  validates :climate, presence: true
  validates :temp_high, presence: true
  validates :temp_low, presence: true
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  def index
    @races = Race.all.by_name_date
  end
  
  def show
    @race = Race.find(params[:id])
    @reviews = Review.where(race: @race, approved: true).by_item
  end
end

app/views/races/index.html.erb
<div class="fullwidth">
  <img class="media" src="/assets/races_banner.jpg" alt="A Cattle Dog with a sign saying 'Good luck Dad! Run Fast! Love you Lots!'">
</div>

<div class="row text-center page-title">
  <hr>
  <h1>Races with Product Reviews</h1>
  <hr>
</div>

<table>
  <tr>
    <th>Name</th>
    <th>Location</th>
    <th>Distance</th>
    <th>Max Temp</th>
    <th>Min Temp</th>
  </tr>
  <% @races.each do |race| %>
    <tr class="text-center race">
      <td><%= link_to "#{race.date.year} #{race.name}", race_path(race) %></td>
      <td><%= race.location %></td>
      <td><%= race.distance %></td>
      <td><%= race.temp_high %></td>
      <td><%= race.temp_low %></td>
    </tr>
  <% end %>
</table>

app/views/races/show.html.erb
<div class="fullwidth">
  <img class="media" src="/assets/races_banner.jpg" alt="A Cattle Dog with a sign saying 'Good luck Dad! Run Fast! Love you Lots!'">
</div>
<div class="row text-center">
</br>
  <%= link_to "All Races", races_path, class: "callout button" %>
</div>
<div class="row text-center page-title">
  <hr>
  <h1><%= @race.date.year %> <%= @race.name %></h1>
  <h3>Race Details</h3>
  <p>Location: <%= @race.location %></p>
  <p>Distance: <%= @race.distance %></p>
  <p>Maximum Temperature (F): <%= @race.temp_high %></p>
  <p>Minimum Temperature (F): <%= @race.temp_low %></p>
  <p>Climate: <%= @race.climate %></p>
  <hr>
  <h2>Product Reviews</h2>
  <hr>
</div>

<table>
  <tr>
    <th>Product Name</th>
    <th>Rating</th>
    <th>Date</th>
    <th>Comments</th>
    <th>User</th>
  </tr>
  <% @reviews.each do |review| %>
    <tr class="text-center review">
      <td><%= link_to "#{review.item.brand} #{review.item.model}", item_path(review.item) %></td>
      <td><%= review.rating %></td>
      <td><%= review.created_at %></td>
      <td><%= review.comments %></td>
      <td><%= link_to "#{review.user.strava_id}", "https://www.strava.com/athletes/#{review.user.strava_id}" %></td>
    </tr>
  <% end %>
</table>

<div class="row text-center">
  <%= link_to "Powered by Dark Sky", "https://darksky.net/poweredby/" %>
</div>