config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"
  
  resources :users, only: [:show]
  resources :reviews, only: [:new, :create]
  resources :races, only: [:index, :show]
  
  namespace :admin do
    resources :reviews, only: [:index, :update]
  end
  
  namespace :items do
    resources :hydration_packs, only: [:index]
    resources :outerwear, only: [:index]
    resources :shoes, only: [:index]
    resources :base_layers, only: [:index]
  end
  resources :items, only: [:show]
  
  get "/auth/strava/callback", to: "sessions#create"
  get "/logout", to: "sessions#destroy"
end

app/views/partials/_brand_checkbox_filter.html.erb
<div class="filter-options-container text-center">
  <h5>Brands:
    <% brands.each do |brand| %>
      <%= check_box_tag 'brands[]', brand, true, class: "brand-checkboxes", id: "#{brand}-checkbox" %>
      <label for='<%= brand %>-checkbox'><h5><%= brand %></h5></label>
    <% end %>
  </h5>
</div>

app/views/partials/_footer.html.erb
<div class="callout footer">
  <div class="row">
    <h5>UltraSwagger.com</h5>
    <p>
      admin@ultraswagger.run</br>
      Copyright 2016</br>
    </p>
  </div>
</div>

app/views/partials/_item_reviews_table.html.erb
<table>
  <tr>
    <th>User</th>
    <th>Review Date</th>
    <th>Rating</th>
    <th>Race</th>
    <th>Comments</th>
  </tr>
  <% reviews.each do |review| %>
    <tr class="user-review">
      <td><%= link_to review.user.strava_id, "https://www.strava.com/athletes/#{review.user.strava_id}" %>
      <td><%= review.created_at.to_date %></td>
      <td><%= review.rating %></td>
      <td><%= link_to "#{review.race.name}", race_path(review.race) %></td>
      <td><%= review.comments %></td>
    </tr>
  <% end %>
</table>

app/views/partials/_items_display.html.erb
<div class="row large-up-3 medium-up-2">
  <% items.each do |item| %>
    <div class='column index-item-container', data-brand="<%= item.brand %>">
      <div class='column text-center index-item'>
        <%= link_to "#{item.brand} #{item.model}", item_path(item), class: "button callout" %>
        <%= image_tag(item.image_path, alt: item.brand + " " + item.model, class: "index-item-image") %>
        <br>
        <br>
      </div>
    </div>
  <% end %>
</div>

app/views/partials/_new_review_button.html.erb
<div class="row text-center">
  <a href="/reviews/new" class="callout button">Submit A Product Review</a>
</div>

app/views/partials/_top_navbar.html.erb
<nav class="fixed-nav-bar text-center">
  <div class="top-bar-left">
    <ul class="menu">
      <li><%= link_to "Ultra Swagger", root_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <% if current_user %>
        <li class="top-bar-text">Welcome, <%= current_user.firstname %>!</li>
        <% if current_admin? %>
          <li><%= link_to "Admin Functions", admin_reviews_path %></li>
        <% end %>
        <li><%= link_to "My Reviews", user_path(current_user) %></li>
        <li><%= link_to "Submit A Review", new_review_path %>
        <li><%= link_to "Logout", "/logout" %></li>
      <% else %>
        <li><%= link_to "Login with Strava", "/auth/strava" %></li>
      <% end %>
    </ul>
  </div>
</nav> 
<div class="top-dead-space">
</div>

app/views/partials/_user_reviews_table.html.erb
<table>
  <tr>
    <th>Review Date</th>
    <th>Item Name</th>
    <th>Rating</th>
    <th>Race</th>
    <th>Comments</th>
    <th>Admin Comments</th>
  </tr>
  <% reviews.each do |sub_review| %>
    <div class='user-review'>
      <tr>
        <td><%= sub_review.created_at.to_date %></td>
        <td><%= sub_review.item.brand + " " + sub_review.item.model %></td>
        <td><%= sub_review.rating %></td>
        <td><%= link_to "#{sub_review.race.name}", race_path(sub_review.race) %></td>
        <td><%= sub_review.comments %></td>
        <td><%= sub_review.admin_comments %></td>
      </tr>
    </div>
  <% end %>
</table>